CREATE TABLE IF NOT EXISTS messages(
	id SERIAL PRIMARY KEY,
	user_id VARCHAR NOT NULL,
	user_name VARCHAR NOT NULL,
	channel VARCHAR NOT NULL,
	text VARCHAR NOT NULL,
	timestamp TIMESTAMPTZ NOT NULL
);